import { ComponentPrototypeType } from '@music163/tango-helpers';
import { InstancePrototypes, StylePrototypes } from './common';

export const AutoComplete: ComponentPrototypeType = {
  name: 'AutoComplete',
  title: '自动完成',
  package: '@music163/antd',
  icon: 'icon-zidongwancheng',
  help: '输入框自动完成功能，可提供输入建议/辅助提示能力',
  type: 'element',
  props: [
    ...StylePrototypes,
    ...InstancePrototypes,
    {
      name: 'width',
      title: '输入框宽度',
      setter: 'textSetter',
    },
    {
      name: 'allowClear',
      title: '支持清除',
      setter: 'boolSetter',
    },
    {
      name: 'autoFocus',
      title: '自动获取焦点',
      setter: 'boolSetter',
      group: 'advanced',
    },
    {
      name: 'backfill',
      title: '选中项回填到输入框',
      tip: '使用键盘选择选项的时候把选中项回填到输入框中',
      setter: 'boolSetter',
      group: 'advanced',
    },
    // {
    //   name: 'children',
    //   title: '填充的数据源',
    //   setter: 'expressionSetter',
    // },
    // {
    //   name: 'children',
    //   title: '自定义输入框',
    //   setter: 'expressionSetter',
    //   defaultValue: '<Input />',
    // },
    {
      name: 'defaultActiveFirstOption',
      title: '默认高亮第一个选项',
      setter: 'boolSetter',
      group: 'advanced',
    },
    {
      name: 'defaultOpen',
      title: '默认展开下拉菜单',
      setter: 'boolSetter',
      group: 'advanced',
    },
    {
      name: 'defaultValue',
      title: '默认选中的条目',
      setter: 'textSetter',
    },
    {
      name: 'disabled',
      title: '是否禁用',
      setter: 'boolSetter',
    },
    {
      name: 'dropdownClassName',
      title: '下拉菜单classname',
      setter: 'textSetter',
      group: 'advanced',
    },
    {
      name: 'dropdownMatchSelectWidth',
      title: '下拉菜单和选择器同宽',
      tip: '默认将设置 min-width，当值小于选择框宽度时会被忽略。false 时会关闭虚拟滚动',
      setter: 'boolSetter',
      group: 'advanced',
    },
    {
      name: 'filterOption',
      title: '根据输入项进行筛选',
      tip: '当其为一个函数时，会接收 inputValue option 两个参数，当 option 符合筛选条件时，应返回 true，反之则返回 false',
      setter: 'boolSetter',
      group: 'advanced',
    },
    {
      name: 'getPopupContainer',
      title: '菜单渲染父节点',
      tip: '默认渲染到 body 上，如果你遇到菜单滚动定位问题，试试修改为滚动的区域，并相对其定位。',
      setter: 'expressionSetter',
      group: 'advanced',
    },
    {
      name: 'notFoundContent',
      title: '下拉列表为空时的内容',
      setter: 'expressionSetter',
      group: 'advanced',
    },
    { name: 'open', title: '展开下拉菜单', setter: 'boolSetter' },
    {
      name: 'options',
      title: '下拉数据源',
      tip: '渲染效果比直接通过jsx定义好',
      setter: 'expressionSetter',
      initValue: [{ value: 'option1' }, { value: 'option2' }, { value: 'option3' }],
    },
    { name: 'placeholder', title: '输入框提示', setter: 'textSetter', initValue: 'input here' },
    { name: 'value', title: '指定当前选中的条目', setter: 'textSetter' },
    { name: 'onBlur', title: '失去焦点时的回调', setter: 'actionSetter', group: 'event' },
    {
      name: 'onChange',
      title: 'onChange事件',
      setter: 'actionSetter',
      group: 'event',
      autoCompleteOptions: ['(currentActiveLink)=>{}'],
    },
    {
      name: 'onDropdownVisibleChange',
      title: '展开下拉菜单的回调',
      setter: 'actionSetter',
      group: 'event',
    },
    { name: 'onFocus', title: '获得焦点时的回调', setter: 'actionSetter', group: 'event' },
    {
      name: 'onSearch',
      title: '搜索补全项的时候调用',
      setter: 'actionSetter',
      group: 'event',
    },
    {
      name: 'onSelect',
      title: '被选中时调用',
      setter: 'actionSetter',
      group: 'event',
    },
  ],
};
